export type JoinTour = {
  slug: string;
  code: string;
  tag: string;
  bookedCount: number;
  featuredOnHome?: boolean;
  featuredDestination?: boolean;
  homeOrder?: number;
  destinationOrder?: number;
  salesBadges: string[];
  destination: string;
  durationDays: number;
  priceValue: number;
  travelMonths: string[];
  menuTags: string[];
  title: string;
  subtitle: string;
  duration: string;
  highlight: string;
  food: string;
  locations: string[];
  travelDates: string[];
  price: string;
  image: string;
  imageClassName: string;
  suitableFor: string[];
  included: string[];
  itinerary: { day: string; title: string; text: string }[];
};

/*
แก้ข้อมูลทัวร์จอยทัวร์ที่ไฟล์นี้ไฟล์เดียว

วิธีเพิ่มทัวร์ใหม่:
1. คัดลอก object ของทัวร์เดิม 1 อันด้านล่าง
2. วางเพิ่มใน array `joinTours`
3. แก้ค่าทุกช่องให้เป็นข้อมูลทัวร์ใหม่

ข้อสำคัญ:
- `slug` ต้องไม่ซ้ำกับทัวร์อื่น เพราะใช้เป็น URL
- `price` คือข้อความที่แสดงบนหน้าเว็บ เช่น "25,900.-"
- `priceValue` คือเลขล้วนสำหรับระบบกรองราคา เช่น 25900
- `duration` คือข้อความแสดงผล เช่น "5 วัน 4 คืน"
- `durationDays` คือเลขจำนวนวันสำหรับระบบกรอง เช่น 5
- `travelMonths` ใช้สำหรับตัวกรองเดือน เช่น ["เม.ย.", "พ.ค."]
- `travelDates` ใช้แสดงผลจริงบนการ์ดและหน้ารายละเอียด
- `menuTags` ใช้จับกลุ่มกับปุ่ม Quick Menu เช่น "ขายดี", "ธรรมชาติ", "เมืองใหญ่", "ครอบครัว", "หนาว", "คุมงบ"
- `salesBadges` คือป้ายขายที่ขึ้นบนรายการทัวร์ เช่น ["ขายดี", "ใหม่"] หรือ ["เหลือไม่กี่ที่"]
- `imageClassName` ปกติใช้ "object-center" ถ้ารูปครอปไม่สวยค่อยปรับ
- `featuredOnHome` ใส่ `true` ถ้าต้องการให้ทัวร์นี้มีสิทธิ์ขึ้นหน้าแรก
- `homeOrder` เลขน้อยขึ้นก่อน สำหรับจัดลำดับหน้าแรก
- `featuredDestination` ใส่ `true` ถ้าต้องการให้เมืองนี้ขึ้น section เมืองท่องเที่ยวยอดนิยม
- `destinationOrder` เลขน้อยขึ้นก่อน สำหรับจัดลำดับเมืองในหน้าแรก
*/

/*
Template สำหรับเพิ่มทัวร์ใหม่

{
  slug: "kunming-dali-lijiang-6d5n",
  code: "CP-KM-6508",
  tag: "JOIN TOUR",
  bookedCount: 10,
  featuredOnHome: true,
  featuredDestination: true,
  homeOrder: 6,
  destinationOrder: 6,
  salesBadges: ["ใหม่"],
  destination: "คุนหมิง",
  durationDays: 6,
  priceValue: 31900,
  travelMonths: ["ต.ค.", "พ.ย."],
  menuTags: ["ธรรมชาติ", "ครอบครัว"],
  title: "คุนหมิง-ต้าหลี่-ลี่เจียง 6 วัน 5 คืน",
  subtitle: "คำโปรยสั้นของทัวร์นี้",
  duration: "6 วัน 5 คืน",
  highlight: "จุดเด่นหลักของทัวร์นี้",
  food: "แนวอาหารหรือเมนูเด่น",
  locations: ["เมือง/สถานที่ 1", "เมือง/สถานที่ 2", "เมือง/สถานที่ 3"],
  travelDates: ["ต.ค. - พ.ย. 68", "เดินทางหลายรอบ"],
  price: "31,900.-",
  image: "/images/your-tour.jpg",
  imageClassName: "object-center",
  suitableFor: ["ครอบครัว", "สายธรรมชาติ"],
  included: ["สิ่งที่รวม 1", "สิ่งที่รวม 2", "สิ่งที่รวม 3"],
  itinerary: [
    { day: "Day 1", title: "หัวข้อวันแรก", text: "รายละเอียดสั้น" },
    { day: "Day 2", title: "หัวข้อวันที่สอง", text: "รายละเอียดสั้น" },
  ],
}
*/

export const joinTours: JoinTour[] = [
  {
    // URL ของทัวร์นี้: /join-tours/beijing-5d4n
    slug: "beijing-5d4n",
    // รหัสทัวร์ที่โชว์บนหน้าเว็บ
    code: "CP-BJ-5401",
    // ประเภทป้ายบนรูป
    tag: "JOIN TOUR",
    // จำนวนคนที่จองแล้ว
    bookedCount: 14,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 1,
    destinationOrder: 1,
    // ป้ายขายบนรายการทัวร์
    salesBadges: ["ขายดี"],
    // เมืองหลัก ใช้กับระบบกรอง
    destination: "ปักกิ่ง",
    // จำนวนวันแบบตัวเลข ใช้กับระบบกรอง
    durationDays: 5,
    // ราคาแบบตัวเลข ใช้กับระบบกรอง
    priceValue: 25900,
    // เดือนที่ใช้กรอง
    travelMonths: ["ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย."],
    // หมวด Quick Menu ที่ทัวร์นี้ควรไปอยู่
    menuTags: ["ขายดี", "เมืองใหญ่", "ครอบครัว", "คุมงบ"],
    // ชื่อแพ็กเกจที่แสดงบนการ์ด
    title: "ปักกิ่ง 5 วัน 4 คืน",
    // คำโปรยสั้น
    subtitle: "เส้นทางคลาสสิกสำหรับคนอยากเที่ยวจีนครั้งแรกแบบครบแลนด์มาร์ก",
    // ระยะเวลาแบบข้อความ
    duration: "5 วัน 4 คืน",
    // ไฮไลต์หลักของทริป
    highlight: "ไฮไลต์กำแพงเมืองจีน พระราชวังต้องห้าม และจัตุรัสเทียนอันเหมิน",
    // แนวอาหารของทัวร์นี้
    food: "อาหารจีนเหนือ เป็ดปักกิ่ง และเมนูท้องถิ่นยอดนิยม",
    // เมืองหรือสถานที่เด่น 2-4 จุด
    locations: ["กำแพงเมืองจีน", "พระราชวังต้องห้าม", "จัตุรัสเทียนอันเหมิน"],
    // ข้อความช่วงเดินทางที่โชว์บนหน้าเว็บ
    travelDates: ["ก.พ. - มิ.ย. 67", "เดินทางได้หลายรอบ"],
    // ราคาแบบข้อความที่โชว์จริง
    price: "25,900.-",
    // รูปแพ็กเกจหรือรูปหลักของทัวร์
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Forbidden_City.jpg",
    // ตำแหน่งรูปเวลา crop
    imageClassName: "object-[center_58%]",
    // ทัวร์นี้เหมาะกับใคร
    suitableFor: ["มือใหม่เที่ยวจีน", "ครอบครัว", "คนชอบแลนด์มาร์กดัง"],
    // สิ่งที่รวมในโปรแกรม
    included: ["โรงแรมตามมาตรฐานโปรแกรม", "รถรับส่งและไกด์", "อาหารตามระบุ", "หัวหน้าทัวร์ดูแล"],
    // โปรแกรมรายวันแบบย่อ
    itinerary: [
      { day: "Day 1", title: "เดินทางถึงปักกิ่ง", text: "รับคณะเข้าสู่ที่พักและพักผ่อนตามอัธยาศัยก่อนเริ่มเที่ยววันถัดไป" },
      { day: "Day 2", title: "พระราชวังต้องห้าม - เทียนอันเหมิน", text: "เที่ยวแลนด์มาร์กประวัติศาสตร์หลักของปักกิ่งแบบเต็มวัน" },
      { day: "Day 3", title: "กำแพงเมืองจีน", text: "ขึ้นชมกำแพงเมืองจีนพร้อมเก็บภาพมุมไฮไลต์ยอดนิยม" },
      { day: "Day 4", title: "เมืองเก่าและช้อปปิ้ง", text: "แวะย่านเมืองเก่า คาเฟ่ และแหล่งช้อปปิ้งที่คนไทยนิยม" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับโดยสวัสดิภาพ" },
    ],
  },
  {
    slug: "shanghai-hangzhou-4d3n",
    code: "CP-SH-4304",
    tag: "JOIN TOUR",
    bookedCount: 12,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 2,
    destinationOrder: 2,
    salesBadges: ["ใหม่"],
    destination: "เซี่ยงไฮ้",
    durationDays: 4,
    priceValue: 29900,
    travelMonths: ["ทุกเดือน"],
    menuTags: ["เมืองใหญ่", "ขายดี"],
    title: "เซี่ยงไฮ้-หางโจว 4 วัน 3 คืน",
    subtitle: "เที่ยวเมืองทันสมัยคู่เมืองโรแมนติก เหมาะกับคนอยากได้ทั้งช้อปและวิวสวย",
    duration: "4 วัน 3 คืน",
    highlight: "ชมมหานครเซี่ยงไฮ้และพักผ่อนริมทะเลสาบซีหูแบบครบจุดดัง",
    food: "เสี่ยวหลงเปา อาหารเซี่ยงไฮ้ และเมนูสไตล์เจียงหนาน",
    locations: ["หอไข่มุก", "หาดไว่ทาน", "ทะเลสาบซีหู"],
    travelDates: ["ออกเดินทางทุกสัปดาห์", "เริ่มกรุ๊ป 20 ท่าน"],
    price: "29,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Shanghai_skyline.jpg",
    imageClassName: "object-[center_62%]",
    suitableFor: ["สายถ่ายรูป", "คู่รัก", "คนอยากเที่ยวเมืองใหญ่"],
    included: ["โรงแรมใจกลางเมือง", "รถโค้ชตลอดทริป", "อาหารหลักตามโปรแกรม", "ทีมงานช่วยดูแลก่อนเดินทาง"],
    itinerary: [
      { day: "Day 1", title: "ถึงเซี่ยงไฮ้", text: "เริ่มต้นทริปด้วยการเช็กอินและเดินเล่นย่านใจกลางเมือง" },
      { day: "Day 2", title: "เซี่ยงไฮ้เต็มวัน", text: "เที่ยวหอไข่มุก หาดไว่ทาน และแลนด์มาร์กยอดนิยม" },
      { day: "Day 3", title: "หางโจว - ทะเลสาบซีหู", text: "นั่งรถสู่หางโจว ชมบรรยากาศทะเลสาบและเมืองเก่าสุดโรแมนติก" },
      { day: "Day 4", title: "เดินทางกลับ", text: "ซื้อของฝากและเดินทางกลับตามเที่ยวบิน" },
    ],
  },
  {
    slug: "zhangjiajie-6d5n",
    code: "CP-ZJJ-6507",
    tag: "JOIN TOUR",
    bookedCount: 17,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 3,
    destinationOrder: 4,
    salesBadges: ["ขายดี", "เหลือไม่กี่ที่"],
    destination: "จางเจียเจี้ย",
    durationDays: 6,
    priceValue: 28900,
    travelMonths: ["เม.ย.", "พ.ค.", "มิ.ย."],
    menuTags: ["ธรรมชาติ", "ขายดี"],
    title: "จางเจียเจี้ย 6 วัน 5 คืน",
    subtitle: "ทริปธรรมชาติยอดฮิตสำหรับคนที่อยากเห็นภูเขาอวตารของจริง",
    duration: "6 วัน 5 คืน",
    highlight: "สัมผัสวิวเขาหินอวตาร เทียนเหมินซาน และสะพานแก้วสุดอลังการ",
    food: "อาหารหูหนานรสเข้มข้น พร้อมเมนูพื้นเมืองขึ้นชื่อ",
    locations: ["เทียนเหมินซาน", "สะพานแก้ว", "อุทยานภูเขาอวตาร"],
    travelDates: ["เม.ย. - มิ.ย. 67", "มีหัวหน้าทัวร์ดูแล"],
    price: "28,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Zhangjiajie_National_Forest_Park.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายธรรมชาติ", "สายถ่ายภาพ", "คนชอบวิวอลังการ"],
    included: ["กระเช้าและค่าเข้าตามโปรแกรม", "หัวหน้าทัวร์ดูแล", "ที่พักตามมาตรฐาน", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "เดินทางถึงจางเจียเจี้ย", text: "รับคณะเข้าสู่โรงแรมและเตรียมพร้อมสำหรับการเที่ยวธรรมชาติเต็มรูปแบบ" },
      { day: "Day 2", title: "เทียนเหมินซาน", text: "ขึ้นกระเช้าชมวิวผาหินและทางเดินกระจกสุดตื่นตา" },
      { day: "Day 3", title: "สะพานแก้ว", text: "เยือนสะพานแก้วชื่อดังและจุดชมวิวระดับไฮไลต์" },
      { day: "Day 4", title: "ภูเขาอวตาร", text: "เก็บภาพอุทยานแห่งชาติและเสาหินทรงเอกลักษณ์" },
      { day: "Day 5", title: "เที่ยวต่อในเมือง", text: "แวะช้อปและสัมผัสบรรยากาศท้องถิ่น" },
      { day: "Day 6", title: "เดินทางกลับ", text: "เดินทางกลับพร้อมความประทับใจจากธรรมชาติระดับโลก" },
    ],
  },
  {
    slug: "chengdu-jiuzhaigou-6d5n",
    code: "CP-CD-6505",
    tag: "JOIN TOUR",
    bookedCount: 15,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 4,
    destinationOrder: 3,
    salesBadges: ["แนะนำ"],
    destination: "เฉิงตู",
    durationDays: 6,
    priceValue: 35900,
    travelMonths: ["เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค."],
    menuTags: ["ธรรมชาติ", "ครอบครัว"],
    title: "เฉิงตู-จิ่วจ้ายโกว 6 วัน 5 คืน",
    subtitle: "แพนด้า ธรรมชาติ และวัฒนธรรมเสฉวนในทริปเดียว",
    duration: "6 วัน 5 คืน",
    highlight: "เที่ยวครบแพนด้า จิ่วจ้ายโกว เมืองโบราณ และธรรมชาติเสฉวน",
    food: "อาหารเสฉวนรสต้นตำรับ และหม้อไฟเฉิงตู",
    locations: ["ศูนย์แพนด้า", "จิ่วจ้ายโกว", "เมืองโบราณ"],
    travelDates: ["ออกเดินทางหลายรอบ", "เหมาะกับครอบครัว"],
    price: "35,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_Panda_%2846774337332%29.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "คนชอบธรรมชาติ", "คนอยากเห็นแพนด้า"],
    included: ["รถเดินทางระหว่างเมือง", "ที่พักหลายคืนตามโปรแกรม", "อาหารจีนเสฉวน", "ทีมงานช่วยดูแลตลอดทริป"],
    itinerary: [
      { day: "Day 1", title: "ถึงเฉิงตู", text: "รับคณะและเข้าที่พักเพื่อพักผ่อนก่อนเริ่มโปรแกรม" },
      { day: "Day 2", title: "ศูนย์แพนด้า", text: "เยือนศูนย์แพนด้าและจุดท่องเที่ยวเด่นในเฉิงตู" },
      { day: "Day 3", title: "เดินทางสู่จิ่วจ้ายโกว", text: "ชมวิวระหว่างทางและเข้าสู่พื้นที่ธรรมชาติยอดนิยม" },
      { day: "Day 4", title: "เที่ยวจิ่วจ้ายโกว", text: "เก็บภาพทะเลสาบสีฟ้า น้ำตก และวิวภูเขา" },
      { day: "Day 5", title: "เมืองโบราณ", text: "แวะเที่ยวเมืองเก่าและเลือกซื้อของฝาก" },
      { day: "Day 6", title: "เดินทางกลับ", text: "สรุปทริปและเดินทางกลับโดยสวัสดิภาพ" },
    ],
  },
  {
    slug: "harbin-6d4n",
    code: "CP-HB-6409",
    tag: "JOIN TOUR",
    bookedCount: 18,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 5,
    destinationOrder: 8,
    salesBadges: ["ขายดี", "เหลือไม่กี่ที่"],
    destination: "ฮาร์บิน",
    durationDays: 6,
    priceValue: 33900,
    travelMonths: ["ธ.ค.", "ม.ค.", "ก.พ."],
    menuTags: ["หนาว", "ขายดี"],
    title: "ฮาร์บิน 6 วัน 4 คืน",
    subtitle: "ทริปฤดูหนาวสำหรับคนอยากสัมผัสเมืองหิมะและเทศกาลน้ำแข็งชื่อดัง",
    duration: "6 วัน 4 คืน",
    highlight: "ชมเทศกาลน้ำแข็ง เมืองหิมะ และแลนด์มาร์กคลาสสิกแห่งฮาร์บิน",
    food: "อาหารจีนตะวันออกเฉียงเหนือ และเมนูอุ่นร้อนรับอากาศหนาว",
    locations: ["เทศกาลน้ำแข็ง", "โบสถ์เซนต์โซเฟีย", "ถนนจงยาง"],
    travelDates: ["ธ.ค. 67 - ก.พ. 68", "เทศกาลหิมะสุดอลังการ"],
    price: "33,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Harbin_Ice_%26_Snow_Festival_2026.jpg",
    imageClassName: "object-center",
    suitableFor: ["คนชอบอากาศหนาว", "สายเทศกาล", "สายถ่ายรูปกลางคืน"],
    included: ["เสื้อกันหนาวคำแนะนำก่อนเดินทาง", "รถรับส่งตลอดทริป", "ที่พักตามโปรแกรม", "หัวหน้าทัวร์ดูแล"],
    itinerary: [
      { day: "Day 1", title: "ถึงฮาร์บิน", text: "เช็กอินและเตรียมพร้อมสำหรับโปรแกรมฤดูหนาว" },
      { day: "Day 2", title: "โบสถ์เซนต์โซเฟีย - ถนนจงยาง", text: "เที่ยวแลนด์มาร์กสำคัญของเมืองและโซนเดินเล่นยอดนิยม" },
      { day: "Day 3", title: "เทศกาลน้ำแข็ง", text: "ชมแสง สี และประติมากรรมน้ำแข็งขนาดใหญ่" },
      { day: "Day 4", title: "เมืองหิมะและกิจกรรมหนาว", text: "สนุกกับบรรยากาศหิมะและมุมถ่ายภาพเต็มวัน" },
      { day: "Day 5", title: "พักผ่อนและช้อป", text: "เลือกซื้อของฝากและพักผ่อนตามอัธยาศัย" },
      { day: "Day 6", title: "เดินทางกลับ", text: "เดินทางกลับพร้อมประสบการณ์ฤดูหนาวสุดประทับใจ" },
    ],
  },
  {
    slug: "kunming-dali-lijiang-6d5n",
    code: "CP-KM-6508",
    tag: "JOIN TOUR",
    bookedCount: 10,
    featuredOnHome: true,
    featuredDestination: true,
    homeOrder: 6,
    destinationOrder: 6,
    salesBadges: ["ใหม่"],
    destination: "คุนหมิง",
    durationDays: 6,
    priceValue: 31900,
    travelMonths: ["ต.ค.", "พ.ย."],
    menuTags: ["ธรรมชาติ", "ครอบครัว"],
    title: "คุนหมิง-ต้าหลี่-ลี่เจียง 6 วัน 5 คืน",
    subtitle: "ทริปเมืองสวยอากาศดี เหมาะกับคนชอบธรรมชาติและเมืองเก่า",
    duration: "6 วัน 5 คืน",
    highlight: "ชมเมืองเก่าลี่เจียง ทะเลสาบเอ๋อร์ไห่ และภูเขาหิมะมังกรหยก",
    food: "อาหารยูนนาน เห็ดหม้อไฟ และเมนูพื้นเมืองรสละมุน",
    locations: ["ลี่เจียง", "ต้าหลี่", "ภูเขาหิมะมังกรหยก"],
    travelDates: ["ต.ค. - พ.ย. 68", "เดินทางหลายรอบ"],
    price: "31,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lijiang,_old_town_%286170338646%29.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "สายธรรมชาติ", "สายถ่ายรูป"],
    included: ["โรงแรมตามโปรแกรม", "รถรับส่ง", "ไกด์ท้องถิ่น", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "เดินทางถึงคุนหมิง", text: "รับคณะและเข้าที่พักเพื่อเตรียมเริ่มทริปในวันถัดไป" },
      { day: "Day 2", title: "คุนหมิง - ต้าหลี่", text: "เดินทางสู่ต้าหลี่และชมทะเลสาบเอ๋อร์ไห่" },
      { day: "Day 3", title: "เมืองเก่าต้าหลี่", text: "เดินเล่นเมืองเก่าและชิมอาหารพื้นเมือง" },
      { day: "Day 4", title: "ลี่เจียง", text: "เที่ยวเมืองเก่ามรดกโลกและมุมถ่ายภาพยอดนิยม" },
      { day: "Day 5", title: "ภูเขาหิมะมังกรหยก", text: "ขึ้นชมวิวภูเขาและธรรมชาติรอบลี่เจียง" },
      { day: "Day 6", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับโดยสวัสดิภาพ" },
    ],
  },
  {
    slug: "guilin-yangshuo-5d4n",
    code: "CP-GL-5406",
    tag: "JOIN TOUR",
    bookedCount: 11,
    featuredDestination: true,
    destinationOrder: 5,
    salesBadges: ["แนะนำ"],
    destination: "กุ้ยหลิน",
    durationDays: 5,
    priceValue: 27900,
    travelMonths: ["มี.ค.", "เม.ย.", "ต.ค.", "พ.ย."],
    menuTags: ["ธรรมชาติ", "คุมงบ"],
    title: "กุ้ยหลิน-หยางซั่ว 5 วัน 4 คืน",
    subtitle: "ทริปสายน้ำและภูเขาหินปูน บรรยากาศโรแมนติกเที่ยวสบาย",
    duration: "5 วัน 4 คืน",
    highlight: "ล่องเรือแม่น้ำหลีเจียง ชมวิวหยางซั่วและเขางวงช้าง",
    food: "อาหารกวางสีและเมนูท้องถิ่นสไตล์จีนตอนใต้",
    locations: ["แม่น้ำหลีเจียง", "หยางซั่ว", "เขางวงช้าง"],
    travelDates: ["มี.ค. - เม.ย. 68", "ต.ค. - พ.ย. 68"],
    price: "27,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Guilin_Li_River.jpg",
    imageClassName: "object-center",
    suitableFor: ["คู่รัก", "สายธรรมชาติ", "คนชอบเที่ยวสบาย"],
    included: ["ล่องเรือตามโปรแกรม", "โรงแรม", "รถรับส่ง", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงกุ้ยหลิน", text: "รับคณะเข้าสู่ที่พักและพักผ่อน" },
      { day: "Day 2", title: "เขางวงช้าง", text: "ชมแลนด์มาร์กสำคัญของกุ้ยหลิน" },
      { day: "Day 3", title: "ล่องเรือแม่น้ำหลีเจียง", text: "ชมวิวภูเขาหินปูนสวยงามตลอดเส้นทาง" },
      { day: "Day 4", title: "หยางซั่ว", text: "เที่ยวเมืองน่ารักและถนนคนเดิน" },
      { day: "Day 5", title: "เดินทางกลับ", text: "ส่งคณะกลับพร้อมความประทับใจ" },
    ],
  },
  {
    slug: "xian-luoyang-5d4n",
    code: "CP-XA-5410",
    tag: "JOIN TOUR",
    bookedCount: 8,
    featuredDestination: true,
    destinationOrder: 7,
    salesBadges: ["ใหม่"],
    destination: "ซีอาน",
    durationDays: 5,
    priceValue: 30900,
    travelMonths: ["มี.ค.", "เม.ย.", "ก.ย.", "ต.ค."],
    menuTags: ["เมืองใหญ่", "ครอบครัว"],
    title: "ซีอาน-ลั่วหยาง 5 วัน 4 คืน",
    subtitle: "เส้นทางประวัติศาสตร์จีน เหมาะกับคนชอบเรื่องราวอารยธรรมโบราณ",
    duration: "5 วัน 4 คืน",
    highlight: "ชมสุสานทหารดินเผา ถ้ำหลงเหมิน และกำแพงเมืองซีอาน",
    food: "อาหารสไตล์ซีอาน บะหมี่ท้องถิ่น และของว่างมุสลิมสตรีท",
    locations: ["สุสานทหารดินเผา", "กำแพงเมืองซีอาน", "ถ้ำหลงเหมิน"],
    travelDates: ["มี.ค. - เม.ย. 68", "ก.ย. - ต.ค. 68"],
    price: "30,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terracotta_Army%2C_View_of_Pit_1.jpg",
    imageClassName: "object-center",
    suitableFor: ["คนชอบประวัติศาสตร์", "ครอบครัว", "มือใหม่เที่ยวจีน"],
    included: ["โรงแรม", "ไกด์", "รถโค้ช", "ค่าเข้าตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงซีอาน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "สุสานทหารดินเผา", text: "เที่ยวแลนด์มาร์กระดับโลกของจีน" },
      { day: "Day 3", title: "ซีอานเมืองเก่า", text: "ปั่นจักรยานบนกำแพงเมืองและเดินเล่นมุสลิมสตรีท" },
      { day: "Day 4", title: "ลั่วหยาง", text: "เยือนถ้ำหลงเหมินและวัดสำคัญ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "chongqing-wulong-5d4n",
    code: "CP-CQ-5403",
    tag: "JOIN TOUR",
    bookedCount: 16,
    salesBadges: ["ขายดี"],
    destination: "ฉงชิ่ง",
    durationDays: 5,
    priceValue: 28900,
    travelMonths: ["มี.ค.", "เม.ย.", "พ.ค.", "ต.ค."],
    menuTags: ["ธรรมชาติ", "เมืองใหญ่", "ขายดี"],
    title: "ฉงชิ่ง-อู่หลง 5 วัน 4 คืน",
    subtitle: "ทริปเมืองภูเขาสุดฮิตและธรรมชาติอลังการ เดินทางคุ้มค่า",
    duration: "5 วัน 4 คืน",
    highlight: "ชมหลุมฟ้า สะพานสวรรค์ และแลนด์มาร์กเมืองฉงชิ่ง",
    food: "หม้อไฟฉงชิ่งและเมนูเสฉวนรสจัดจ้าน",
    locations: ["หงหยาต้ง", "อู่หลง", "หลุมฟ้า"],
    travelDates: ["มี.ค. - พ.ค. 68", "ต.ค. 68"],
    price: "28,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Hongya_Cave_2020.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายถ่ายรูป", "สายกิน", "คนชอบเมืองมีสไตล์"],
    included: ["โรงแรม", "ค่าเข้าหลุมฟ้า", "รถรับส่ง", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงฉงชิ่ง", text: "รับคณะและเช็กอินเข้าสู่ที่พัก" },
      { day: "Day 2", title: "เที่ยวเมืองฉงชิ่ง", text: "ชมรถไฟทะลุตึก หงหยาต้ง และวิวกลางคืน" },
      { day: "Day 3", title: "อู่หลง", text: "เดินทางสู่อู่หลงและเที่ยวธรรมชาติชื่อดัง" },
      { day: "Day 4", title: "หลุมฟ้า", text: "ชมหลุมฟ้าและสะพานสวรรค์สุดอลังการ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "ส่งคณะเดินทางกลับ" },
    ],
  },
  {
    slug: "guangzhou-shenzhen-4d3n",
    code: "CP-GZ-4302",
    tag: "JOIN TOUR",
    bookedCount: 9,
    salesBadges: ["คุมงบ"],
    destination: "กวางโจว",
    durationDays: 4,
    priceValue: 23900,
    travelMonths: ["ทุกเดือน"],
    menuTags: ["เมืองใหญ่", "คุมงบ"],
    title: "กวางโจว-เซินเจิ้น 4 วัน 3 คืน",
    subtitle: "ทริปเมืองเศรษฐกิจทันสมัย เหมาะกับสายช้อปและคนอยากลองจีนยุคใหม่",
    duration: "4 วัน 3 คืน",
    highlight: "เที่ยวกวางโจว เซินเจิ้น ช้อปปิ้ง และชมเมืองสมัยใหม่",
    food: "ติ่มซำกวางตุ้งและอาหารจีนกวางตุ้งสไตล์ดั้งเดิม",
    locations: ["กวางโจว", "เซินเจิ้น", "ย่านช้อปปิ้ง"],
    travelDates: ["ออกเดินทางทุกเดือน", "เริ่มเดินทางได้ไว"],
    price: "23,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Canton_Tower_2020.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายช้อป", "คนคุมงบ", "คนชอบเมืองทันสมัย"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารหลักตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงกวางโจว", text: "เช็กอินและพักผ่อน" },
      { day: "Day 2", title: "เที่ยวกวางโจว", text: "ชมเมืองและช้อปย่านสำคัญ" },
      { day: "Day 3", title: "เซินเจิ้น", text: "นั่งรถสู่เซินเจิ้นและเที่ยวเมืองสมัยใหม่" },
      { day: "Day 4", title: "เดินทางกลับ", text: "ซื้อของฝากและเดินทางกลับ" },
    ],
  },
  {
    slug: "huangshan-hongcun-5d4n",
    code: "CP-HS-5407",
    tag: "JOIN TOUR",
    bookedCount: 7,
    salesBadges: ["แนะนำ"],
    destination: "หวงซาน",
    durationDays: 5,
    priceValue: 32900,
    travelMonths: ["มี.ค.", "เม.ย.", "พ.ย."],
    menuTags: ["ธรรมชาติ"],
    title: "หวงซาน-หงชุน 5 วัน 4 คืน",
    subtitle: "ทริปภูเขาสวยระดับตำนานและหมู่บ้านโบราณสุดคลาสสิก",
    duration: "5 วัน 4 คืน",
    highlight: "ชมเขาหวงซาน หมู่บ้านหงชุน และทะเลหมอกยามเช้า",
    food: "อาหารอันฮุยและเมนูท้องถิ่นสไตล์บ้าน ๆ",
    locations: ["เขาหวงซาน", "หงชุน", "ถนนโบราณถุนซี"],
    travelDates: ["มี.ค. - เม.ย. 68", "พ.ย. 68"],
    price: "32,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Huangshan_Mountain.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายธรรมชาติ", "สายถ่ายรูป", "คนชอบเมืองโบราณ"],
    included: ["กระเช้า", "โรงแรม", "รถรับส่ง", "อาหารตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงหวงซาน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "ขึ้นเขาหวงซาน", text: "ชมวิวภูเขาและทะเลหมอก" },
      { day: "Day 3", title: "เที่ยวต่อบนเขา", text: "เก็บภาพธรรมชาติและจุดชมวิว" },
      { day: "Day 4", title: "หงชุน", text: "เที่ยวหมู่บ้านโบราณและถนนเก่า" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "fujian-tulou-xiamen-5d4n",
    code: "CP-FJ-5409",
    tag: "JOIN TOUR",
    bookedCount: 6,
    salesBadges: ["ใหม่"],
    destination: "เซียะเหมิน",
    durationDays: 5,
    priceValue: 29900,
    travelMonths: ["เม.ย.", "พ.ค.", "ต.ค.", "พ.ย."],
    menuTags: ["ครอบครัว", "เมืองใหญ่"],
    title: "เซียะเหมิน-ถู่โหลว 5 วัน 4 คืน",
    subtitle: "เที่ยวเมืองชายทะเลและสถาปัตยกรรมจีนแคะอันโด่งดัง",
    duration: "5 วัน 4 คืน",
    highlight: "ชมบ้านดินถู่โหลว เกาะกู่ลั่งอวี่ และบรรยากาศเมืองทะเลเซียะเหมิน",
    food: "ซีฟู้ดพื้นเมืองและอาหารฮกเกี้ยนสไตล์ต้นตำรับ",
    locations: ["ถู่โหลว", "เกาะกู่ลั่งอวี่", "เซียะเหมิน"],
    travelDates: ["เม.ย. - พ.ค. 68", "ต.ค. - พ.ย. 68"],
    price: "29,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tulou.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "คนชอบเมืองทะเล", "คนชอบวัฒนธรรม"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "ค่าเรือข้ามเกาะ"],
    itinerary: [
      { day: "Day 1", title: "ถึงเซียะเหมิน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เกาะกู่ลั่งอวี่", text: "ชมเมืองเก่าสไตล์ยุโรปและวิวทะเล" },
      { day: "Day 3", title: "บ้านดินถู่โหลว", text: "เยือนสถาปัตยกรรมจีนแคะชื่อดัง" },
      { day: "Day 4", title: "เที่ยวเมืองเซียะเหมิน", text: "เดินเล่นย่านฮิปและริมทะเล" },
      { day: "Day 5", title: "เดินทางกลับ", text: "ส่งคณะกลับ" },
    ],
  },
  {
    slug: "zhuhai-macau-4d3n",
    code: "CP-ZH-4308",
    tag: "JOIN TOUR",
    bookedCount: 13,
    salesBadges: ["ขายดี"],
    destination: "จูไห่",
    durationDays: 4,
    priceValue: 26900,
    travelMonths: ["ทุกเดือน"],
    menuTags: ["เมืองใหญ่", "ขายดี", "คุมงบ"],
    title: "จูไห่-มาเก๊า 4 วัน 3 คืน",
    subtitle: "ทริปสั้นเที่ยวสบาย เหมาะกับคนอยากได้ทั้งจีนและบรรยากาศยุโรป",
    duration: "4 วัน 3 คืน",
    highlight: "ชมจูไห่ Lovers Road และแวะเที่ยวมาเก๊าแบบครบรส",
    food: "อาหารกวางตุ้งและเมนูสไตล์โปรตุเกสในมาเก๊า",
    locations: ["จูไห่", "Lovers Road", "มาเก๊า"],
    travelDates: ["ออกเดินทางทุกเดือน", "เหมาะกับทริปสั้น"],
    price: "26,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Macau_Skyline.jpg",
    imageClassName: "object-center",
    suitableFor: ["คนมีวันลาน้อย", "สายช้อป", "คู่รัก"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงจูไห่", text: "รับคณะเข้าสู่ที่พัก" },
      { day: "Day 2", title: "เที่ยวจูไห่", text: "ชมวิวเมืองและแลนด์มาร์กริมทะเล" },
      { day: "Day 3", title: "มาเก๊า", text: "เดินทางไปมาเก๊าและเที่ยวแลนด์มาร์กสำคัญ" },
      { day: "Day 4", title: "เดินทางกลับ", text: "สรุปทริปและเดินทางกลับ" },
    ],
  },
  {
    slug: "tibet-lhasa-6d5n",
    code: "CP-TB-6511",
    tag: "JOIN TOUR",
    bookedCount: 5,
    salesBadges: ["แนะนำ"],
    destination: "ลาซา",
    durationDays: 6,
    priceValue: 45900,
    travelMonths: ["พ.ค.", "มิ.ย.", "ก.ย."],
    menuTags: ["ธรรมชาติ"],
    title: "ทิเบต-ลาซา 6 วัน 5 คืน",
    subtitle: "ทริปพิเศษสำหรับคนอยากสัมผัสวัฒนธรรมบนหลังคาโลก",
    duration: "6 วัน 5 คืน",
    highlight: "ชมพระราชวังโปตาลา วัดโจคัง และบรรยากาศทิเบตแท้ ๆ",
    food: "อาหารทิเบตและอาหารจีนตะวันตกเฉียงใต้",
    locations: ["พระราชวังโปตาลา", "วัดโจคัง", "ลาซา"],
    travelDates: ["พ.ค. - มิ.ย. 68", "ก.ย. 68"],
    price: "45,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Potala_Palace.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายวัฒนธรรม", "นักเดินทางสายพิเศษ", "คนชอบเส้นทางไม่ซ้ำ"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "เอกสารตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงลาซา", text: "พักผ่อนเพื่อปรับตัวกับระดับความสูง" },
      { day: "Day 2", title: "พระราชวังโปตาลา", text: "เที่ยวแลนด์มาร์กสำคัญของทิเบต" },
      { day: "Day 3", title: "วัดโจคัง", text: "สัมผัสวัฒนธรรมและวิถีชีวิตท้องถิ่น" },
      { day: "Day 4", title: "เที่ยวเมืองลาซา", text: "เดินเล่นและชิมอาหารพื้นเมือง" },
      { day: "Day 5", title: "เก็บบรรยากาศ", text: "เที่ยวตามโปรแกรมต่อเนื่อง" },
      { day: "Day 6", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "wuhan-yichang-5d4n",
    code: "CP-WH-5404",
    tag: "JOIN TOUR",
    bookedCount: 7,
    salesBadges: ["ใหม่"],
    destination: "อู่ฮั่น",
    durationDays: 5,
    priceValue: 26900,
    travelMonths: ["มี.ค.", "เม.ย.", "พ.ย."],
    menuTags: ["เมืองใหญ่", "คุมงบ"],
    title: "อู่ฮั่น-อี๋ชาง 5 วัน 4 คืน",
    subtitle: "เที่ยวเมืองสำคัญริมแม่น้ำแยงซีและแลนด์มาร์กสมัยใหม่",
    duration: "5 วัน 4 คืน",
    highlight: "ชมวิวแม่น้ำแยงซี เขื่อนสามผา และย่านเมืองสำคัญของอู่ฮั่น",
    food: "อาหารหูเป่ยและเมนูเส้นสไตล์ท้องถิ่น",
    locations: ["อู่ฮั่น", "เขื่อนสามผา", "อี๋ชาง"],
    travelDates: ["มี.ค. - เม.ย. 68", "พ.ย. 68"],
    price: "26,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Wuhan_Yangtze_River_Bridge.jpg",
    imageClassName: "object-center",
    suitableFor: ["มือใหม่เที่ยวจีน", "คนชอบเมืองริมแม่น้ำ", "สายคุมงบ"],
    included: ["โรงแรม", "ค่าเข้าตามโปรแกรม", "รถรับส่ง", "อาหารหลัก"],
    itinerary: [
      { day: "Day 1", title: "ถึงอู่ฮั่น", text: "รับคณะเข้าสู่ที่พัก" },
      { day: "Day 2", title: "เที่ยวอู่ฮั่น", text: "ชมสะพานและวิวแม่น้ำแยงซี" },
      { day: "Day 3", title: "เขื่อนสามผา", text: "เดินทางสู่อี๋ชางและชมเขื่อนสำคัญ" },
      { day: "Day 4", title: "เที่ยวต่อ", text: "เก็บบรรยากาศเมืองและธรรมชาติริมแม่น้ำ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "inner-mongolia-5d4n",
    code: "CP-IM-5412",
    tag: "JOIN TOUR",
    bookedCount: 6,
    salesBadges: ["แนะนำ"],
    destination: "มองโกเลียใน",
    durationDays: 5,
    priceValue: 34900,
    travelMonths: ["มิ.ย.", "ก.ค.", "ส.ค."],
    menuTags: ["ธรรมชาติ", "ครอบครัว"],
    title: "มองโกเลียใน 5 วัน 4 คืน",
    subtitle: "ทุ่งหญ้ากว้างสุดสายตาและประสบการณ์พักกระโจมแบบไม่เหมือนใคร",
    duration: "5 วัน 4 คืน",
    highlight: "ขี่ม้ากลางทุ่งหญ้า ชมวิถีชาวมองโกล และพักกระโจม",
    food: "บาร์บีคิวสไตล์มองโกลและเมนูเนื้อท้องถิ่น",
    locations: ["ทุ่งหญ้า", "กระโจมมองโกล", "ทะเลทราย"],
    travelDates: ["มิ.ย. - ส.ค. 68", "เหมาะกับฤดูร้อน"],
    price: "34,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Grassland_Inner_Mongolia.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "สายธรรมชาติ", "คนอยากลองประสบการณ์ใหม่"],
    included: ["ที่พักกระโจม", "รถรับส่ง", "กิจกรรมตามโปรแกรม", "อาหารหลัก"],
    itinerary: [
      { day: "Day 1", title: "ถึงมองโกเลียใน", text: "รับคณะและเดินทางเข้าสู่ที่พัก" },
      { day: "Day 2", title: "ทุ่งหญ้า", text: "สัมผัสทุ่งหญ้าและขี่ม้า" },
      { day: "Day 3", title: "วัฒนธรรมท้องถิ่น", text: "ชมการแสดงและวิถีชีวิตชาวมองโกล" },
      { day: "Day 4", title: "ทะเลทราย", text: "ทำกิจกรรมกลางแจ้งและชมพระอาทิตย์ตก" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "sichuan-leshan-emei-5d4n",
    code: "CP-SC-5408",
    tag: "JOIN TOUR",
    bookedCount: 9,
    salesBadges: ["ครอบครัว"],
    destination: "เล่อซาน",
    durationDays: 5,
    priceValue: 30900,
    travelMonths: ["มี.ค.", "เม.ย.", "ต.ค."],
    menuTags: ["ธรรมชาติ", "ครอบครัว"],
    title: "เล่อซาน-ง้อไบ๊ 5 วัน 4 คืน",
    subtitle: "ทริปไหว้พระและธรรมชาติ เหมาะกับคนชอบเส้นทางสงบและมีเรื่องราว",
    duration: "5 วัน 4 คืน",
    highlight: "ชมพระใหญ่เล่อซานและขุนเขาง้อไบ๊ชื่อดัง",
    food: "อาหารเสฉวนและเมนูเจพื้นเมืองบางมื้อ",
    locations: ["พระใหญ่เล่อซาน", "ง้อไบ๊", "เฉิงตู"],
    travelDates: ["มี.ค. - เม.ย. 68", "ต.ค. 68"],
    price: "30,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Leshan_Giant_Buddha.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "สายบุญ", "คนชอบภูเขา"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "ค่าเข้าตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงเฉิงตู", text: "รับคณะและเดินทางสู่ที่พัก" },
      { day: "Day 2", title: "พระใหญ่เล่อซาน", text: "เที่ยวแลนด์มาร์กสำคัญและล่องเรือชมวิว" },
      { day: "Day 3", title: "ง้อไบ๊", text: "ขึ้นเขาและชมธรรมชาติ" },
      { day: "Day 4", title: "เที่ยวต่อ", text: "เก็บภาพและพักผ่อนตามโปรแกรม" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "nanjing-suzhou-5d4n",
    code: "CP-NJ-5405",
    tag: "JOIN TOUR",
    bookedCount: 12,
    salesBadges: ["ขายดี"],
    destination: "นานกิง",
    durationDays: 5,
    priceValue: 28900,
    travelMonths: ["มี.ค.", "เม.ย.", "ต.ค.", "พ.ย."],
    menuTags: ["เมืองใหญ่", "ครอบครัว"],
    title: "นานกิง-ซูโจว 5 วัน 4 คืน",
    subtitle: "เที่ยวเมืองประวัติศาสตร์และสวนจีนสวยงามในจังหวะสบาย",
    duration: "5 วัน 4 คืน",
    highlight: "ชมกำแพงเมืองนานกิง วัดสำคัญ และสวนซูโจวระดับโลก",
    food: "อาหารเจียงซู รสกลมกล่อม และของว่างพื้นเมือง",
    locations: ["นานกิง", "ซูโจว", "สวนจีนโบราณ"],
    travelDates: ["มี.ค. - เม.ย. 68", "ต.ค. - พ.ย. 68"],
    price: "28,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Suzhou_Garden.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "คนชอบสวนจีน", "สายประวัติศาสตร์"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารหลักตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงนานกิง", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวเมืองนานกิง", text: "ชมแลนด์มาร์กสำคัญและเมืองเก่า" },
      { day: "Day 3", title: "ซูโจว", text: "เดินทางและเที่ยวสวนจีนชื่อดัง" },
      { day: "Day 4", title: "เที่ยวต่อ", text: "เก็บบรรยากาศเมืองน้ำและช้อปเบา ๆ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "changsha-furong-zjj-6d5n",
    code: "CP-CS-6513",
    tag: "JOIN TOUR",
    bookedCount: 14,
    salesBadges: ["ขายดี"],
    destination: "ฉางซา",
    durationDays: 6,
    priceValue: 29900,
    travelMonths: ["เม.ย.", "พ.ค.", "มิ.ย."],
    menuTags: ["ธรรมชาติ", "ขายดี"],
    title: "ฉางซา-ฝูหรง-จางเจียเจี้ย 6 วัน 5 คืน",
    subtitle: "เที่ยวครบเมืองฮิตและธรรมชาติในทริปเดียว คุ้มค่าและถ่ายรูปสวย",
    duration: "6 วัน 5 คืน",
    highlight: "ชมเมืองโบราณฝูหรง เทียนเหมินซาน และมุมฮิตในฉางซา",
    food: "อาหารหูหนานรสจัดและเมนูพื้นเมืองชื่อดัง",
    locations: ["ฉางซา", "ฝูหรงเจิ้น", "เทียนเหมินซาน"],
    travelDates: ["เม.ย. - มิ.ย. 68", "มีรอบออกต่อเนื่อง"],
    price: "29,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Furong_Town.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายถ่ายรูป", "สายธรรมชาติ", "คนชอบทริปคุ้ม"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "ค่าเข้าตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงฉางซา", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวฉางซา", text: "ชมแลนด์มาร์กเมืองและย่านดัง" },
      { day: "Day 3", title: "ฝูหรงเจิ้น", text: "เที่ยวเมืองโบราณกลางน้ำตก" },
      { day: "Day 4", title: "จางเจียเจี้ย", text: "เดินทางและเที่ยวธรรมชาติ" },
      { day: "Day 5", title: "เทียนเหมินซาน", text: "ขึ้นกระเช้าและชมทางเดินกระจก" },
      { day: "Day 6", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "qingdao-5d4n",
    code: "CP-QD-5401",
    tag: "JOIN TOUR",
    bookedCount: 8,
    salesBadges: ["ใหม่"],
    destination: "ชิงเต่า",
    durationDays: 5,
    priceValue: 27900,
    travelMonths: ["พ.ค.", "มิ.ย.", "ก.ย."],
    menuTags: ["เมืองใหญ่", "ครอบครัว"],
    title: "ชิงเต่า 5 วัน 4 คืน",
    subtitle: "เมืองทะเลบรรยากาศดี เที่ยวง่าย เดินเล่นสบายและอาหารอร่อย",
    duration: "5 วัน 4 คืน",
    highlight: "ชมเมืองทะเล อาคารยุโรป และบรรยากาศริมชายหาดชิงเต่า",
    food: "ซีฟู้ดสดและอาหารชานตงพื้นเมือง",
    locations: ["ชายทะเลชิงเต่า", "เมืองเก่า", "โรงเบียร์ชิงเต่า"],
    travelDates: ["พ.ค. - มิ.ย. 68", "ก.ย. 68"],
    price: "27,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Qingdao_coastline.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "คนชอบทะเล", "คนอยากเที่ยวสบาย"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงชิงเต่า", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวเมืองเก่า", text: "ชมย่านอาคารเก่าสไตล์ยุโรป" },
      { day: "Day 3", title: "ทะเลและชายหาด", text: "พักผ่อนและถ่ายรูปริมทะเล" },
      { day: "Day 4", title: "โรงเบียร์และเมือง", text: "เที่ยวแลนด์มาร์กสำคัญของเมือง" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "sanya-hainan-5d4n",
    code: "CP-SY-5402",
    tag: "JOIN TOUR",
    bookedCount: 10,
    salesBadges: ["แนะนำ"],
    destination: "ซานย่า",
    durationDays: 5,
    priceValue: 33900,
    travelMonths: ["มี.ค.", "เม.ย.", "พ.ย.", "ธ.ค."],
    menuTags: ["ครอบครัว", "เมืองใหญ่"],
    title: "ซานย่า-ไหหลำ 5 วัน 4 คืน",
    subtitle: "ทริปทะเลจีนตอนใต้ บรรยากาศรีสอร์ตและพักผ่อนเต็มที่",
    duration: "5 วัน 4 คืน",
    highlight: "เที่ยวชายหาดซานย่า พักผ่อนริมทะเล และช้อปสบาย",
    food: "ซีฟู้ดไหหลำ ไก่ไหหลำ และเมนูจีนตอนใต้",
    locations: ["ซานย่า", "ชายหาด", "ย่านช้อปปิ้ง"],
    travelDates: ["มี.ค. - เม.ย. 68", "พ.ย. - ธ.ค. 68"],
    price: "33,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sanya_Beach.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "คู่รัก", "คนอยากพักผ่อน"],
    included: ["โรงแรมรีสอร์ต", "รถรับส่ง", "ไกด์", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงซานย่า", text: "รับคณะและเช็กอินที่พักริมทะเล" },
      { day: "Day 2", title: "เที่ยวชายหาด", text: "พักผ่อนและทำกิจกรรมริมทะเล" },
      { day: "Day 3", title: "เที่ยวเมือง", text: "เดินเล่นและช้อปเบา ๆ" },
      { day: "Day 4", title: "พักผ่อนตามอัธยาศัย", text: "เก็บบรรยากาศรีสอร์ต" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "urumqi-kanas-7d6n",
    code: "CP-XJ-7601",
    tag: "JOIN TOUR",
    bookedCount: 4,
    salesBadges: ["แนะนำ"],
    destination: "ซินเจียง",
    durationDays: 7,
    priceValue: 49900,
    travelMonths: ["ก.ย.", "ต.ค."],
    menuTags: ["ธรรมชาติ"],
    title: "ซินเจียง-คานาสือ 7 วัน 6 คืน",
    subtitle: "เส้นทางธรรมชาติสุดอลังการสำหรับคนอยากเห็นจีนอีกมุมหนึ่ง",
    duration: "7 วัน 6 คืน",
    highlight: "ชมทะเลสาบคานาสือ ทุ่งหญ้า และวิวธรรมชาติขนาดใหญ่ของซินเจียง",
    food: "อาหารฮาลาลและเมนูพื้นเมืองซินเจียง",
    locations: ["อุรุมชี", "คานาสือ", "ทุ่งหญ้า"],
    travelDates: ["ก.ย. - ต.ค. 68", "รอบพิเศษฤดูใบไม้เปลี่ยนสี"],
    price: "49,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kanas_Lake.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายธรรมชาติจริงจัง", "คนชอบเส้นทางพิเศษ", "สายถ่ายรูป"],
    included: ["โรงแรม", "รถรับส่ง", "ค่าเข้าตามระบุ", "อาหารตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงอุรุมชี", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เดินทางสู่คานาสือ", text: "ชมวิวธรรมชาติระหว่างทาง" },
      { day: "Day 3", title: "คานาสือ", text: "เที่ยวทะเลสาบและจุดชมวิว" },
      { day: "Day 4", title: "เที่ยวต่อ", text: "เก็บภาพธรรมชาติและหมู่บ้านท้องถิ่น" },
      { day: "Day 5", title: "ทุ่งหญ้า", text: "ชมทุ่งหญ้าและวิถีชีวิตพื้นเมือง" },
      { day: "Day 6", title: "กลับสู่อุรุมชี", text: "พักผ่อนก่อนเดินทางกลับ" },
      { day: "Day 7", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "shenyang-dalian-5d4n",
    code: "CP-SY-5407",
    tag: "JOIN TOUR",
    bookedCount: 7,
    salesBadges: ["คุมงบ"],
    destination: "ต้าเหลียน",
    durationDays: 5,
    priceValue: 25900,
    travelMonths: ["เม.ย.", "พ.ค.", "ก.ย."],
    menuTags: ["เมืองใหญ่", "คุมงบ"],
    title: "เสิ่นหยาง-ต้าเหลียน 5 วัน 4 คืน",
    subtitle: "เที่ยวสองเมืองภาคตะวันออกเฉียงเหนือ บรรยากาศสบายและเดินทางง่าย",
    duration: "5 วัน 4 คืน",
    highlight: "ชมเมืองตากอากาศต้าเหลียนและแลนด์มาร์กสำคัญของเสิ่นหยาง",
    food: "ซีฟู้ดและอาหารจีนตะวันออกเฉียงเหนือ",
    locations: ["ต้าเหลียน", "เสิ่นหยาง", "ชายทะเล"],
    travelDates: ["เม.ย. - พ.ค. 68", "ก.ย. 68"],
    price: "25,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dalian_Cityscape.jpg",
    imageClassName: "object-center",
    suitableFor: ["คนคุมงบ", "คนชอบเมืองริมทะเล", "ครอบครัว"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงเสิ่นหยาง", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวเสิ่นหยาง", text: "ชมแลนด์มาร์กสำคัญของเมือง" },
      { day: "Day 3", title: "เดินทางสู่ต้าเหลียน", text: "เที่ยวเมืองริมทะเล" },
      { day: "Day 4", title: "พักผ่อนและช้อป", text: "เที่ยวต่อในเมืองและชายทะเล" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "wuxi-suzhou-shanghai-5d4n",
    code: "CP-WX-5406",
    tag: "JOIN TOUR",
    bookedCount: 11,
    salesBadges: ["ขายดี"],
    destination: "อู๋ซี",
    durationDays: 5,
    priceValue: 29900,
    travelMonths: ["ทุกเดือน"],
    menuTags: ["เมืองใหญ่", "ขายดี"],
    title: "อู๋ซี-ซูโจว-เซี่ยงไฮ้ 5 วัน 4 คืน",
    subtitle: "สามเมืองยอดนิยมในทริปเดียว เหมาะกับคนอยากเที่ยวครบแบบคุ้มค่า",
    duration: "5 วัน 4 คืน",
    highlight: "ชมเมืองน้ำ ซูโจว และปิดท้ายที่เซี่ยงไฮ้แบบครบไฮไลต์",
    food: "อาหารเจียงหนานและเมนูเซี่ยงไฮ้ยอดนิยม",
    locations: ["อู๋ซี", "ซูโจว", "เซี่ยงไฮ้"],
    travelDates: ["ออกเดินทางทุกเดือน", "รอบต่อเนื่อง"],
    price: "29,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Suzhou_Canal.jpg",
    imageClassName: "object-center",
    suitableFor: ["มือใหม่เที่ยวจีน", "สายช้อป", "ครอบครัว"],
    included: ["โรงแรม", "รถโค้ช", "ไกด์", "อาหารตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงอู๋ซี", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวอู๋ซี", text: "ชมเมืองและทะเลสาบ" },
      { day: "Day 3", title: "ซูโจว", text: "เที่ยวสวนและเมืองน้ำ" },
      { day: "Day 4", title: "เซี่ยงไฮ้", text: "เที่ยวแลนด์มาร์กสำคัญและช้อปปิ้ง" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "zibo-qufu-jinan-5d4n",
    code: "CP-SD-5414",
    tag: "JOIN TOUR",
    bookedCount: 5,
    salesBadges: ["ใหม่"],
    destination: "จี่หนาน",
    durationDays: 5,
    priceValue: 28900,
    travelMonths: ["มี.ค.", "เม.ย.", "ต.ค."],
    menuTags: ["ครอบครัว", "เมืองใหญ่"],
    title: "จี่หนาน-ชวีฟู่-จือปั๋ว 5 วัน 4 คืน",
    subtitle: "เที่ยวเมืองวัฒนธรรมและเมืองอาหารฮิตแบบไม่ซ้ำใคร",
    duration: "5 วัน 4 คืน",
    highlight: "ชมบ้านขงจื๊อ เที่ยวจือปั๋ว และสัมผัสบรรยากาศเมืองชานตง",
    food: "บาร์บีคิวจือปั๋วและอาหารชานตง",
    locations: ["จี่หนาน", "ชวีฟู่", "จือปั๋ว"],
    travelDates: ["มี.ค. - เม.ย. 68", "ต.ค. 68"],
    price: "28,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Confucius_Temple_Qufu.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายกิน", "คนชอบวัฒนธรรม", "คนอยากลองเมืองใหม่"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "อาหารตามระบุ"],
    itinerary: [
      { day: "Day 1", title: "ถึงจี่หนาน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวจี่หนาน", text: "ชมบ่อน้ำพุและบรรยากาศเมือง" },
      { day: "Day 3", title: "ชวีฟู่", text: "เยือนบ้านและวัดขงจื๊อ" },
      { day: "Day 4", title: "จือปั๋ว", text: "ชิมบาร์บีคิวชื่อดังและเที่ยวเมือง" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "ningxia-yinchuan-5d4n",
    code: "CP-NX-5415",
    tag: "JOIN TOUR",
    bookedCount: 4,
    salesBadges: ["แนะนำ"],
    destination: "อิ๋นชวน",
    durationDays: 5,
    priceValue: 31900,
    travelMonths: ["พ.ค.", "ก.ย.", "ต.ค."],
    menuTags: ["ธรรมชาติ", "ครอบครัว"],
    title: "หนิงเซี่ย-อิ๋นชวน 5 วัน 4 คืน",
    subtitle: "สัมผัสทะเลทรายและวัฒนธรรมจีนมุสลิมในเส้นทางไม่ซ้ำใคร",
    duration: "5 วัน 4 คืน",
    highlight: "ชมทะเลทราย แม่น้ำเหลือง และแลนด์มาร์กหนิงเซี่ย",
    food: "อาหารฮาลาลและเมนูท้องถิ่นแบบหนิงเซี่ย",
    locations: ["อิ๋นชวน", "ทะเลทราย", "แม่น้ำเหลือง"],
    travelDates: ["พ.ค. 68", "ก.ย. - ต.ค. 68"],
    price: "31,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Shapotou_Desert.jpg",
    imageClassName: "object-center",
    suitableFor: ["สายธรรมชาติ", "คนอยากลองเส้นทางใหม่", "ครอบครัว"],
    included: ["โรงแรม", "รถรับส่ง", "กิจกรรมทะเลทราย", "อาหารหลัก"],
    itinerary: [
      { day: "Day 1", title: "ถึงอิ๋นชวน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "เที่ยวเมือง", text: "ชมสถานที่สำคัญและวัฒนธรรมท้องถิ่น" },
      { day: "Day 3", title: "ทะเลทราย", text: "ทำกิจกรรมและถ่ายรูปกลางทะเลทราย" },
      { day: "Day 4", title: "แม่น้ำเหลือง", text: "เที่ยวต่อในโซนธรรมชาติ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
  {
    slug: "xiamen-quanzhou-5d4n",
    code: "CP-XM-5416",
    tag: "JOIN TOUR",
    bookedCount: 9,
    salesBadges: ["ใหม่"],
    destination: "เซียะเหมิน",
    durationDays: 5,
    priceValue: 28900,
    travelMonths: ["ก.พ.", "มี.ค.", "พ.ย."],
    menuTags: ["เมืองใหญ่", "ครอบครัว"],
    title: "เซียะเหมิน-เฉวียนโจว 5 วัน 4 คืน",
    subtitle: "เที่ยวเมืองทะเลและเมืองมรดกโลก เหมาะกับคนชอบวัฒนธรรมผสมความชิล",
    duration: "5 วัน 4 คืน",
    highlight: "ชมเกาะกู่ลั่งอวี่และย่านเก่าเฉวียนโจวแบบครบมู้ด",
    food: "ซีฟู้ดและอาหารฮกเกี้ยนสไตล์พื้นเมือง",
    locations: ["เซียะเหมิน", "กู่ลั่งอวี่", "เฉวียนโจว"],
    travelDates: ["ก.พ. - มี.ค. 68", "พ.ย. 68"],
    price: "28,900.-",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gulangyu_Island.jpg",
    imageClassName: "object-center",
    suitableFor: ["ครอบครัว", "สายชิล", "คนชอบเมืองทะเล"],
    included: ["โรงแรม", "รถรับส่ง", "ไกด์", "ค่าเรือตามโปรแกรม"],
    itinerary: [
      { day: "Day 1", title: "ถึงเซียะเหมิน", text: "รับคณะและเข้าที่พัก" },
      { day: "Day 2", title: "กู่ลั่งอวี่", text: "เที่ยวเกาะและย่านเก่าริมทะเล" },
      { day: "Day 3", title: "เฉวียนโจว", text: "ชมมรดกโลกและวัดสำคัญ" },
      { day: "Day 4", title: "เที่ยวเมืองต่อ", text: "พักผ่อนและช้อปเบา ๆ" },
      { day: "Day 5", title: "เดินทางกลับ", text: "เช็กเอาต์และเดินทางกลับ" },
    ],
  },
];

export function getJoinTourBySlug(slug: string) {
  return joinTours.find((tour) => tour.slug === slug);
}
